@extends('invitation.layout')

@push('fonts')
<link rel="preconnect" href="https://fonts.bunny.net">
<link href="https://fonts.bunny.net/css?family=great-vibes:400|cormorant:300,400,600,700|cormorant-sc:400,600&display=swap" rel="stylesheet" />
@endpush

@push('styles')
<link rel="stylesheet" href="{{ asset('css/classic.css') }}">
<link rel="stylesheet" href="{{ asset('css/photo-bg-slideshow.css') }}">
@endpush

@section('content')

{{-- ══════════════════════════════
     FLOATING PETALS (Generated by JavaScript)
══════════════════════════════ --}}
<div id="petals-container"></div>

{{-- ══════════════════════════════
     HERO
══════════════════════════════ --}}
<section class="hero" id="top">

    {{-- Corner ornaments --}}
    <svg class="corner corner-tl" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M2 98 L2 2 L98 2" stroke="#b8892a" stroke-width="1" fill="none" />
        <path d="M2 60 Q 20 50 20 2" stroke="#b8892a" stroke-width="0.6" fill="none" opacity=".5" />
        <circle cx="2" cy="2" r="3" fill="#b8892a" />
        <circle cx="2" cy="98" r="1.5" fill="#b8892a" opacity=".5" />
        <circle cx="98" cy="2" r="1.5" fill="#b8892a" opacity=".5" />
    </svg>
    <svg class="corner corner-tr" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M2 98 L2 2 L98 2" stroke="#b8892a" stroke-width="1" fill="none" />
        <path d="M2 60 Q 20 50 20 2" stroke="#b8892a" stroke-width="0.6" fill="none" opacity=".5" />
        <circle cx="2" cy="2" r="3" fill="#b8892a" />
    </svg>
    <svg class="corner corner-bl" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M2 98 L2 2 L98 2" stroke="#b8892a" stroke-width="1" fill="none" />
        <circle cx="2" cy="2" r="3" fill="#b8892a" />
    </svg>
    <svg class="corner corner-br" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M2 98 L2 2 L98 2" stroke="#b8892a" stroke-width="1" fill="none" />
        <circle cx="2" cy="2" r="3" fill="#b8892a" />
    </svg>

    {{-- Kepada tamu --}}
    @if($guest)
    <div class="hero-eyebrow mb-6">
        <span class="section-tag" style="font-size:.7rem;">Kepada Yang Terhormat</span>
        <p class="font-invitation" style="font-size:clamp(1.8rem,5vw,2.6rem); color:#6b4c1e; line-height:1.2;">
            {{ $guest->guest_name }}
        </p>
    </div>
    @endif

    {{-- Eyebrow --}}
    <div class="hero-eyebrow">
        <div class="ornament mb-4" style="max-width:200px;">
            <div class="ornament-line"></div>
            <div class="ornament-dot"></div>
            <div class="ornament-diamond"></div>
            <div class="ornament-dot"></div>
            <div class="ornament-line"></div>
        </div>
        <span class="section-tag">Undangan Pernikahan</span>
    </div>

    {{-- Names --}}
    <div class="hero-names" style="margin: 12px 0 20px;">
        <h1>{{ $wedding->bride_name }}</h1>
        <span class="ampersand">&amp;</span>
        <h1>{{ $wedding->groom_name }}</h1>
    </div>

    {{-- Date badge --}}
    @if($wedding->event_date)
    <div class="hero-date">
        <div class="badge-date">
            <span class="badge-dot"></span>
            {{ $wedding->event_date->locale('id')->translatedFormat('l, d F Y') }}
            <span class="badge-dot"></span>
        </div>
        @if($wedding->location)
        <p style="font-family:'Cormorant SC',serif; font-size:.68rem; letter-spacing:.3em; color:var(--stone-light); margin-top:10px;">
            {{ $wedding->location }}
        </p>
        @endif
    </div>
    @endif

    {{-- CTA --}}
    <a href="#mempelai" class="scroll-cta hero-cta" style="margin-top:48px;">
        <span>Buka Undangan</span>
        <span class="scroll-arrow"></span>
    </a>
</section>


{{-- ══════════════════════════════
     MEMPELAI
══════════════════════════════ --}}
<section class="mempelai-section" id="mempelai">
    <div class="text-center">
        <span class="section-tag reveal">Yang Berbahagia</span>
        <h2 class="section-title reveal">Dua Hati Bersatu</h2>
        <p class="section-sub reveal">
            Dengan penuh syukur dan kebahagiaan, kami mengumumkan pernikahan putra-putri kami.
        </p>
    </div>

    <div class="mempelai-grid">
        {{-- Mempelai Wanita --}}
        <div class="text-center reveal">
            <div class="mempelai-photo-wrap">
                <div class="mempelai-photo-inner">
                    @if($wedding->bride_photo ?? false)
                    <img src="{{ asset('storage/'.$wedding->bride_photo) }}" alt="{{ $wedding->bride_name }}">
                    @else
                    🌸
                    @endif
                </div>
            </div>
            <div class="mempelai-name">{{ $wedding->bride_name }}</div>
            @if($wedding->bride_fullname ?? false)
            <div class="mempelai-fullname">{{ $wedding->bride_fullname }}</div>
            @endif
            @if(($wedding->bride_father ?? false) || ($wedding->bride_mother ?? false))
            <p class="mempelai-parents">
                Putri dari<br>
                <strong style="color:var(--stone);">
                    {{ $wedding->bride_father ?? '' }}{{ ($wedding->bride_father && $wedding->bride_mother) ? ' & ' : '' }}{{ $wedding->bride_mother ?? '' }}
                </strong>
            </p>
            @endif
        </div>

        {{-- Separator --}}
        <div class="mempelai-sep reveal">&</div>

        {{-- Mempelai Pria --}}
        <div class="text-center reveal">
            <div class="mempelai-photo-wrap">
                <div class="mempelai-photo-inner">
                    @if($wedding->groom_photo ?? false)
                    <img src="{{ asset('storage/'.$wedding->groom_photo) }}" alt="{{ $wedding->groom_name }}">
                    @else
                    🤵
                    @endif
                </div>
            </div>
            <div class="mempelai-name">{{ $wedding->groom_name }}</div>
            @if($wedding->groom_fullname ?? false)
            <div class="mempelai-fullname">{{ $wedding->groom_fullname }}</div>
            @endif
            @if(($wedding->groom_father ?? false) || ($wedding->groom_mother ?? false))
            <p class="mempelai-parents">
                Putra dari<br>
                <strong style="color:var(--stone);">
                    {{ $wedding->groom_father ?? '' }}{{ ($wedding->groom_father && $wedding->groom_mother) ? ' & ' : '' }}{{ $wedding->groom_mother ?? '' }}
                </strong>
            </p>
            @endif
        </div>
    </div>
</section>

{{-- ══════════════════════════════
     FOTO COUPLE (optional)
══════════════════════════════ --}}
@if($wedding->couple_photo)
<section class="couple-photo-section" style="padding:3rem 1rem;background:linear-gradient(135deg,#faf8f3 0%,#f5f1ea 100%);text-align:center;">
    <div class="container" style="max-width:600px;margin:0 auto;">
        <span class="section-tag reveal">Momen Berdua</span>
        <h2 class="section-title reveal" style="margin-bottom:2rem;">Our Special Moment</h2>
        <div class="reveal" style="position:relative;border-radius:12px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,0.15);border:4px solid #d4af37;">
            <img src="{{ asset('storage/' . $wedding->couple_photo) }}" 
                 alt="{{ $wedding->bride_name }} & {{ $wedding->groom_name }}" 
                 style="width:100%;height:auto;display:block;object-fit:cover;max-height:500px;">
        </div>
    </div>
</section>
@endif


{{-- ══════════════════════════════
     AYAT / KUTIPAN
══════════════════════════════ --}}
<section class="ayat-section">
    <p class="ayat-text reveal">
        "{{ $wedding->customText('quote_text', 'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu isteri-isteri dari jenismu sendiri, supaya kamu cenderung dan merasa tenteram kepadanya, dan dijadikan-Nya di antaramu rasa kasih dan sayang.') }}"
    </p>
    <span class="ayat-source reveal">{{ $wedding->customText('quote_source', 'QS. Ar-Rum: 21') }}</span>
</section>


{{-- ══════════════════════════════
     ACARA
══════════════════════════════ --}}
<section class="acara-section" id="acara">
    <div class="text-center">
        <span class="section-tag reveal">Rangkaian Acara</span>
        <h2 class="section-title reveal">Agenda Hari Istimewa</h2>
    </div>

    <div class="acara-cards">
        {{-- Akad --}}
        @if($wedding->akad_date ?? $wedding->event_date)
        <div class="card acara-card reveal">
            <span class="acara-icon">☽</span>
            <div class="acara-type">Akad Nikah</div>
            <div class="acara-title">Ijab Qabul</div>
            <div class="acara-info">
                <strong>{{ ($wedding->akad_date ?? $wedding->event_date)->locale('id')->translatedFormat('l, d F Y') }}</strong>
                {{ $wedding->akad_time ?? '08.00 – 10.00' }} WIB<br><br>
                {{ $wedding->akad_location ?? ($wedding->location ?? 'Lokasi Akad Nikah') }}
            </div>
        </div>
        @endif

        {{-- Resepsi --}}
        <div class="card acara-card reveal">
            <span class="acara-icon">✦</span>
            <div class="acara-type">Resepsi</div>
            <div class="acara-title">{{ $wedding->customText('event_name', 'Walimatul Ursy') }}</div>
            <div class="acara-info">
                <strong>{{ $wedding->event_date->locale('id')->translatedFormat('l, d F Y') }}</strong>
                {{ $wedding->reception_time ?? '11.00 – 14.00' }} WIB<br><br>
                {{ $wedding->reception_location ?? $wedding->location ?? 'Lokasi Resepsi' }}
            </div>
        </div>
    </div>
</section>


{{-- ══════════════════════════════
     COUNTDOWN
══════════════════════════════ --}}
<section class="countdown-section" id="countdown">
    <span class="section-tag reveal">Menuju Hari Bahagia</span>
    <h2 class="section-title reveal">Hitung Mundur</h2>

    <div class="countdown-grid reveal" id="countdown-grid">
        <div class="countdown-item">
            <span class="countdown-num" id="cd-hari">00</span>
            <span class="countdown-lbl">Hari</span>
        </div>
        <div class="countdown-sep">·</div>
        <div class="countdown-item">
            <span class="countdown-num" id="cd-jam">00</span>
            <span class="countdown-lbl">Jam</span>
        </div>
        <div class="countdown-sep">·</div>
        <div class="countdown-item">
            <span class="countdown-num" id="cd-menit">00</span>
            <span class="countdown-lbl">Menit</span>
        </div>
        <div class="countdown-sep">·</div>
        <div class="countdown-item">
            <span class="countdown-num" id="cd-detik">00</span>
            <span class="countdown-lbl">Detik</span>
        </div>
    </div>
</section>


{{-- ══════════════════════════════
     GALLERY
══════════════════════════════ --}}
@php
    $gallPhotos = [];
    if (!empty($isPreview) && !empty($demoPhotos)) {
        $gallPhotos = $demoPhotos;
    } elseif (($wedding->galleries ?? collect())->count() > 0) {
        $gallPhotos = $wedding->galleries->map(fn($g) => asset('storage/'.$g->path))->toArray();
    }
@endphp
@if(($wedding->has_gallery || !empty($isPreview)) && count($gallPhotos) > 0)
<section class="gallery-section" id="galeri">
    <span class="section-tag reveal">Momen Berharga</span>
    <h2 class="section-title reveal">Galeri Foto</h2>
    <p class="section-sub reveal">Setiap foto menyimpan cerita indah perjalanan cinta kami.</p>

    @include('invitation.partials.gallery-innovations', [
        'galleryPhotos'  => $gallPhotos,
        'galleryMode'    => 'slider',
        'galleryBgColor' => '#f7f0e8',
        'galleryAccent'  => 'rgba(163,110,48,0.25)',
    ])
</section>
@endif


{{-- ══════════════════════════════
     LOKASI
══════════════════════════════ --}}
<section class="map-section" id="lokasi">
    <span class="section-tag reveal">Temukan Kami</span>
    <h2 class="section-title reveal">Lokasi Acara</h2>
    @if($wedding->location)
    <p class="section-sub reveal">{{ $wedding->location }}</p>
    @endif

    <div class="map-frame reveal">
        @if($wedding->map_embed ?? false)
        {!! $wedding->map_embed !!}
        @elseif($wedding->map_link ?? false)
        <div class="map-placeholder">
            <span class="map-pin">📍</span>
            <span style="font-family:'Cormorant SC',serif; font-size:.7rem; letter-spacing:.3em;">
                {{ $wedding->location ?? 'Lokasi Acara' }}
            </span>
        </div>
        @else
        <div class="map-placeholder">
            <span class="map-pin">📍</span>
            <span style="font-family:'Cormorant SC',serif; font-size:.7rem; letter-spacing:.3em;">Peta Lokasi</span>
        </div>
        @endif
    </div>

    @if($wedding->map_link ?? false)
    <a href="{{ $wedding->map_link }}" target="_blank" rel="noopener" class="btn-outline reveal">
        Buka di Google Maps
    </a>
    @endif
</section>


{{-- ══════════════════════════════
     AMPLOP DIGITAL
══════════════════════════════ --}}
@if(($wedding->bank_accounts ?? collect())->count() > 0 || ($wedding->bride_bank ?? false) || ($wedding->groom_bank ?? false))
<section class="gift-section" id="amplop">
    <span class="section-tag reveal">Hadiah & Doa</span>
    <h2 class="section-title reveal">Amplop Digital</h2>
    <p class="section-sub reveal">
        Kehadiran dan doa restu Anda adalah hadiah terindah bagi kami. Namun jika berkenan memberikan hadiah, silakan melalui:
    </p>

    <div class="gift-cards">
        {{-- Dynamic bank accounts --}}
        @if($wedding->bank_accounts ?? false)
        @foreach($wedding->bank_accounts as $acc)
        <div class="card gift-card reveal">
            <span class="gift-icon">💳</span>
            <div class="gift-bank">{{ $acc->bank_name }}</div>
            <div class="gift-norek">{{ $acc->account_number }}</div>
            <div class="gift-atas">a/n {{ $acc->account_name }}</div>
            <button class="copy-btn" onclick="copyText('{{ $acc->account_number }}', this)">Salin Nomor</button>
        </div>
        @endforeach
        @else
        {{-- Fallback single fields --}}
        @if($wedding->bride_bank ?? false)
        <div class="card gift-card reveal">
            <span class="gift-icon">💳</span>
            <div class="gift-bank">{{ $wedding->bride_bank }}</div>
            <div class="gift-norek">{{ $wedding->bride_norek }}</div>
            <div class="gift-atas">a/n {{ $wedding->bride_name }}</div>
            <button class="copy-btn" onclick="copyText('{{ $wedding->bride_norek }}', this)">Salin Nomor</button>
        </div>
        @endif
        @if($wedding->groom_bank ?? false)
        <div class="card gift-card reveal">
            <span class="gift-icon">💳</span>
            <div class="gift-bank">{{ $wedding->groom_bank }}</div>
            <div class="gift-norek">{{ $wedding->groom_norek }}</div>
            <div class="gift-atas">a/n {{ $wedding->groom_name }}</div>
            <button class="copy-btn" onclick="copyText('{{ $wedding->groom_norek }}', this)">Salin Nomor</button>
        </div>
        @endif
        @endif
    </div>
</section>
@endif


@include('invitation.partials.guestbook')

{{-- ══════════════════════════════
     RSVP + UCAPAN
══════════════════════════════ --}}
<section class="rsvp-section" id="rsvp">
    <span class="section-tag reveal">Konfirmasi & Ucapan</span>
    <h2 class="section-title" style="color:var(--gold-pale);" class="reveal">Kirimkan Doa Anda</h2>
    <p class="section-sub reveal" style="color:rgba(240,220,168,.65);">
        Mohon konfirmasi kehadiran Anda dan titipkan doa serta ucapan untuk kedua mempelai.
    </p>

    {{-- Success state --}}
    <div class="rsvp-success" id="rsvp-success">
        <span class="rsvp-success-icon">✦</span>
        <p style="font-family:'Great Vibes',cursive; font-size:2rem; color:var(--gold-light);">Terima Kasih</p>
        <p style="color:rgba(240,220,168,.7); font-size:.9rem; margin-top:8px;">
            Konfirmasi dan ucapan Anda telah kami terima. Sampai jumpa di hari bahagia kami! 🌸
        </p>
    </div>

    <form id="rsvp-form" class="rsvp-form reveal" action="{{ route('rsvp.store', $wedding->slug) }}" method="POST">
        @csrf

        <div class="form-row">
            <label for="guest_name">Nama Lengkap</label>
            <input type="text" id="guest_name" name="guest_name"
                value="{{ $guest->guest_name ?? '' }}"
                placeholder="Masukkan nama Anda" required />
        </div>

        <div class="form-row">
            <label for="phone">Nomor WhatsApp <span style="opacity:.4;">(opsional)</span></label>
            <input type="tel" id="phone" name="phone"
                placeholder="+62 8xx xxxx xxxx" />
        </div>

        <div class="form-row">
            <label>Konfirmasi Kehadiran</label>
            <div class="rsvp-hadir-toggle">
                <input type="radio" name="attendance" id="att-hadir" value="hadir" checked>
                <label for="att-hadir">Hadir</label>
                <input type="radio" name="attendance" id="att-mungkin" value="mungkin">
                <label for="att-mungkin">Mungkin</label>
                <input type="radio" name="attendance" id="att-tidak" value="tidak_hadir">
                <label for="att-tidak">Tidak Hadir</label>
            </div>
        </div>

        <div class="form-row" id="row-jumlah">
            <label for="guests_count">Jumlah Tamu</label>
            <input type="number" id="guests_count" name="guests_count" min="1" max="10" value="1" />
        </div>

        <div class="form-row">
            <label for="message">Ucapan & Doa</label>
            <textarea id="message" name="message"
                placeholder="Tuliskan ucapan, doa, dan harapan untuk kedua mempelai..."></textarea>
        </div>

        <button type="submit" class="btn-submit">Kirim Sekarang</button>
    </form>

    {{-- Ucapan wall --}}
    @if(($rsvps ?? collect())->count() > 0)
    <div style="margin-top:60px;" class="reveal">
        <div class="ornament" style="max-width:240px; margin:0 auto 32px;">
            <div class="ornament-line"></div>
            <div class="ornament-dot"></div>
            <div class="ornament-diamond"></div>
            <div class="ornament-dot"></div>
            <div class="ornament-line"></div>
        </div>
        <span class="section-tag">Ucapan & Doa</span>

        <div class="ucapan-list" id="ucapan-list">
            @foreach($rsvps as $rsvp)
            <div class="ucapan-item">
                <div>
                    <span class="ucapan-nama">{{ $rsvp->guest_name }}</span>
                    <span class="ucapan-hadir">
                        · {{ $rsvp->is_attending ? '✓ Hadir' : '✗ Tidak Hadir' }}
                    </span>
                </div>
                @php
                    // Ekstrak pesan dari notes (yang dimulai dengan [RSVP])
                    $message = $rsvp->notes;
                    if (str_contains($message, '[RSVP]')) {
                        $message = trim(str_replace('[RSVP]', '', $message));
                    }
                @endphp
                <p class="ucapan-pesan">{{ $message }}</p>
            </div>
            @endforeach
        </div>
    </div>
    @endif
</section>


{{-- ══════════════════════════════
     FOOTER
══════════════════════════════ --}}
<footer class="footer">
    <div class="ornament" style="max-width:240px; margin:0 auto 32px;">
        <div class="ornament-line"></div>
        <div class="ornament-dot"></div>
        <div class="ornament-diamond"></div>
        <div class="ornament-dot"></div>
        <div class="ornament-line"></div>
    </div>

    <div class="footer-logo">{{ $wedding->bride_name }} & {{ $wedding->groom_name }}</div>

    <p class="footer-note">
        @if($wedding->event_date)
        {{ $wedding->event_date->locale('id')->translatedFormat('l, d F Y') }}<br>
        @endif
        @if($wedding->location)
        {{ $wedding->location }}<br>
        @endif
        <em style="color:var(--gold); font-size:.95rem;">Dengan penuh cinta & kebahagiaan 🌸</em>
    </p>

    <div class="ornament" style="max-width:160px; margin:32px auto;">
        <div class="ornament-line"></div>
        <div class="ornament-diamond" style="width:5px; height:5px;"></div>
        <div class="ornament-line"></div>
    </div>

    <p class="footer-credit">Dibuat dengan ❤ · Laravel 11</p>
</footer>

{{-- ═══ MUSIC PLAYER ═══ --}}
@php
    $_rawMus = null;
    if (!empty($wedding->music_file))  $_rawMus = asset('storage/' . $wedding->music_file);
    elseif (!empty($wedding->music_url)) $_rawMus = $wedding->music_url;
    $_musUrl = null; $_ytId = null;
    if ($_rawMus) {
        if (preg_match('/(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([a-zA-Z0-9_\-]{11})/', $_rawMus, $_ym)) {
            $_ytId = $_ym[1];
        } else { $_musUrl = $_rawMus; }
    }
@endphp
@if(!empty($_musUrl) || !empty($_ytId))
<button id="wp-music-btn" onclick="toggleMusic()" title="Putar Musik" style="position:fixed;bottom:20px;left:16px;z-index:9999;width:44px;height:44px;border-radius:50%;border:2px solid rgba(255,255,255,.25);background:rgba(0,0,0,.55);color:#fff;font-size:20px;cursor:pointer;display:none;align-items:center;justify-content:center;backdrop-filter:blur(8px);transition:all .2s;box-shadow:0 2px 12px rgba(0,0,0,.4);">♪</button>
@endif
@if(!empty($_ytId))
<div style="position:fixed;width:1px;height:1px;overflow:hidden;opacity:0;pointer-events:none;top:-9999px;left:-9999px;" aria-hidden="true"><div id="wp-yt-player"></div></div>
@endif

@endsection

@push('scripts')
<script>
    // Inject data dari Blade ke JavaScript
    window.weddingData = {
        eventDate: '{{ $wedding->event_date->format("Y-m-d") }}',
        csrfToken: '{{ csrf_token() }}'
    };
</script>
<script src="{{ asset('js/classic.js') }}"></script>
<script>
@php
  $_bgList = [];
  if (!empty($isPreview) && !empty($demoPhotos)) {
    $_bgList = array_values($demoPhotos);
  } elseif ($wedding->has_gallery && $wedding->gallery->count() > 0) {
    $_bgList = $wedding->gallery->map(fn($g) => asset('storage/' . $g->path))->toArray();
  }
@endphp
window.bgPhotos = {!! json_encode($_bgList) !!};
</script>
<script src="{{ asset('js/photo-bg-slideshow.js') }}"></script>
@if(!empty($_musUrl) || !empty($_ytId))
@if(!empty($_ytId))<script src="https://www.youtube.com/iframe_api" async defer></script>@endif
<script>window.musicData={url:'{{ $_musUrl ?? "" }}',ytId:'{{ $_ytId ?? "" }}',btnId:'wp-music-btn'};</script>
<script src="{{ asset('js/music-player.js') }}"></script>
@endif
@endpush